on:
  push:
    branches: [ satge ]
name: 🚀 Deploy Stage on SFTP
jobs:
  web-deploy:
    name: 🎉 Deploy Stage
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:

           server: ${{ secrets.STAGE_SFTP_SERVER }}
           username: ${{ secrets.STAGE_SFTP_USERNAME }}
           password: ${{ secrets.STAGE_SFTP_PASSWORD }}
           server-dir: /public_html/
           exclude: |
             */.git
             */.git/**
             */node_modules/*
             */public/*
             */vendor/*
